Repository LeoCosta-dev/T24-Ebanx, pull requests merged in 2023-06, with the labels that each got.

#4 feat: :sparkles: crianção do arquivo yohan.js
  victorMartins.js
  yohan.js
Labels: help wanted

#3 feat: criado arquivo renato css
  Renato.js
  victorVechi.js
Labels: question

#5 VictorVechi => main
  victorMartins.js
Labels: bug
